name: 'Go Example (GHA)'
description: 'A template for a Go-based action'
author: 'Leon Silcott <leon@boasi.io>'
inputs:
  name:
    description: 'The name to greet'
    required: true
  repetition:
    description: 'The number of times to repeat the greeting'
    required: false
    default: '1'

runs:
  using: 'node24'
  main: 'invoke-binary.js'
